### PR TITLE
build: build with GCC toolchain

### PR DESCRIPTION
**Pull request by andryblack**

### CODE REVIEW

**Comment by Andy-Big** [comment]
I beg your pardon for the naive questions, but I'm inexperienced in working with github.
Will it be enough for me to accept this request and that's it? Can there be any conflicts in the future when I change the sources? What do I need to do to keep your changes up to date?

**Comment by andryblack** [comment]
Github merge request is a just branch merge proposal. After accept it is merged to specified branch and we dnt need support it. Just make you future work on merged sources.
Short git tutorial https://proglib.io/p/git-for-half-an-hour

**Comment by Andy-Big** [comment]
OK thanks. I looked at the changes you made and will try to stick to them in the future. Such as UINT instead of uint_32t and the like.

**Comment by Andy-Big** [comment]
I tried to build the project in IAR after merging - everything is fine. Thanks for the modification for GCC :)

**Comment by andryblack** [comment]
> OK thanks. I looked at the changes you made and will try to stick to them in the future. Such as UINT instead of uint_32t and the like.

Its no rule, its fixes only for correct argument types for fatfs methods

**Comment by Andy-Big** [comment]
Got it. I will consider it in future changes :)

**Comment by Andy-Big** [comment]
Я же правильно понял, что Вы из России? :)

**Pull request merged**
